kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-data-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "mariadb-pv"
spec:
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/lib/mariadb-data"
