apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-configs
  labels:
    name: cm-configs
  namespace: default
data:
  service-config.yml: |-
    kaa:
      applications:
        lamppost:
          versions:
            lamppost_v1:
              endpoint-token-trustful-mode:
                enabled: true

    logging:
      level:
        org.kaaproject.cm: TRACE
