apiVersion: v1
kind: ConfigMap
metadata:
  name: epr-configs
  labels:
    name: epr-configs
  namespace: default
data:
  service-config.yml: |-
    kaa:
      applications:
        lamppost:
          versions:
            lamppost_v1:

    logging:
      level:
        org.kaaproject.epr: TRACE
